### ISSUE TITLE
ExtensibleNavigationBarNavigationController initialization crash

### ISSUE THREAD

**Issue by gouen95** [faberNovel/ADNavigationBarExtension#1]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: barAppearance != nil' 

when I'm trying to use ExtensibleNavigationBarNavigationController(rootViewController: someViewController()). 

Appreciate your time.

**Comment by samuel-gallet** [comment]
Hi @gouen95 
Thanks for reporting the issue.
You can bypass this issue by adding this line of codes to your AppDelegate in the `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)`.

let appearance = UINavigationBarAppearance()
appearance.configureWithDefaultBackground()
UINavigationBar
    .appearance(whenContainedInInstancesOf: [ExtensibleNavigationBarNavigationController.self])
    .standardAppearance = appearance

I will fix the initial issue soon

**Comment by samuel-gallet** [comment]
Fixed in version 0.1.3
