### ISSUE TITLE
Fix safe area when setting the child VCs directly

### ISSUE THREAD

**Issue by gaetanzanella** [faberNovel/ADNavigationBarExtension#16]
If we set the view controllers using the `viewControllers` property;
```swift
extensibleNavigationController.viewControllers = [myChildVC]
```
the safe area of the inserted view controllers does not take into account the height of the extension view.

**Comment by samuel-gallet** [comment]
Fixed by https://github.com/faberNovel/ADNavigationBarExtension/pull/17
