### ISSUE TITLE
Extension appears above instead of below the navigation bar when the navigation controller pushes a view controller that hides the navigation bar.

### ISSUE THREAD

**Issue by OmerFlame** [faberNovel/ADNavigationBarExtension#5]
The title says it all.

**Comment by OmerFlame** [comment]
Here is a screen recording of the issue.

https://user-images.githubusercontent.com/17903236/103686010-d4465580-4f96-11eb-8ddf-3540d0ae4f42.MP4

**Comment by samuel-gallet** [comment]
@OmerFlame thanks for reporting the issue. We will fix it as soon as possible

**Comment by samuel-gallet** [comment]
Should be fixed in 1.0.2
