### ISSUE TITLE
Custom transition animations using transitionCoordinator don’t work

### ISSUE THREAD

**Issue by OmerFlame** [faberNovel/ADNavigationBarExtension#9]
I am trying to add an animation to the navigation bar in a `viewWillAppear()` and `viewWillDisappear()` in a view controller which is managed by an `ExtensibleNavigationBarNavigationController` and also normal navigation controllers. The animation is supposed to alter the opacity of the navigation bar's internal `UIVisualEffectView`. In the video I am going to add, you can see that in the first part I am pushing the view controller from a normal `UINavigationController` and it works, but when I try to push the same view controller from an `ExtensibleNavigationBarNavigationController`, the animation doesn't happen at all.

[Imgur link to the screen recording](https://imgur.com/a/z50VzRy)

Please answer as fast as possible, because this is a big issue.

**Comment by samuel-gallet** [comment]
Hi!
Can you give me a sample of your code to animate the opacity of the navigation bar's internal UIVisualEffectView?

**Comment by OmerFlame** [comment]
Instead of giving you just the code here, I'll give you an entire repo.

http://github.com/OmerFlame/AltRant

Go inside the AltRant project, then to Template Views, and then to Profile View and then to ProfileTableViewController.swift.

Then, just find the viewWillAppear and viewWillDisappear methods.

I'm sorry I can't give a direct link, I am writing this on my phone because I am not at home right now 😅

**Comment by samuel-gallet** [comment]
Thanks for providing the code samples.
Unfortunately this feature cannot be handled by the library because you are using private API from UINavigationBar component.
The best I can do is setting the toolbar properties public (used in the ExtensibleNavigationBarNavigationController to fake the UINavigationBar content) in order to allow you using the VisualEffectView on the toolbars

**Comment by OmerFlame** [comment]
Sure thing! That can work.

**Comment by samuel-gallet** [comment]
I just released the version 1.0.3. You can now access to the toolbars used to perform NavigationBar appearance like

**Comment by OmerFlame** [comment]
Thank you!
